export default function Head() {
  return (
    <>
      <title>Luiz Gustavo Farias</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta
        property="og:image"
        content="https://avatars.githubusercontent.com/u/98123114?v=4?s=400"
      />
      <meta property="og:image:alt" content="Full Stack Developer" />
      <meta property="og:type" content="portfolio" />
      <meta property="og:title" content="Luiz Gustavo Farias" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
